import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "./components/header/header";

const poppins = Poppins({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
})

// const poppins = Poppins({ subsets: ["latin"], weights: [ `100`, `200`, `300`, `400`, `500`, `600`, `700`, `800`, `900`]
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Header />
        
        {children}
        </body>
    </html>
  );
}
